// All page components
export {DashboardPage} from './DashboardPage';
export {WorkflowsPage} from './WorkflowsPage';
export {ExecutionsPage} from './ExecutionsPage';
export {TriggersPage} from './TriggersPage';
export {MonitoringPage} from './MonitoringPage';
export {ResourcesPage} from './ResourcesPage';
export {SettingsPage} from './SettingsPage';
export {ExecutionDetailPage} from './ExecutionDetailPage';