// Code generated by modelgen from pkg/models/event.go. DO NOT EDIT.

package models

import "time"

// Event represents an immutable event in the execution event log.
// Events track workflow and node execution progress for observability and replay.
type Event struct {
	ID          string         `json:"id"`
	ExecutionID string         `json:"execution_id"`
	EventType   string         `json:"event_type"`
	Sequence    int64          `json:"sequence"`
	Payload     map[string]any `json:"payload,omitempty"`
	CreatedAt   time.Time      `json:"created_at"`
}

// Event type constants (dot notation for hierarchical categorization).
const (
	// Execution-level events
	EventTypeExecutionStarted   = "execution.started"
	EventTypeExecutionCompleted = "execution.completed"
	EventTypeExecutionFailed    = "execution.failed"
	EventTypeExecutionCancelled = "execution.cancelled"
	EventTypeExecutionPaused    = "execution.paused"
	EventTypeExecutionResumed   = "execution.resumed"
	// Node-level events
	EventTypeNodeStarted   = "node.started"
	EventTypeNodeCompleted = "node.completed"
	EventTypeNodeFailed    = "node.failed"
	EventTypeNodeSkipped   = "node.skipped"
	EventTypeNodeRetrying  = "node.retrying"
	// Wave-level events (parallel execution batches)
	EventTypeWaveStarted   = "wave.started"
	EventTypeWaveCompleted = "wave.completed"
	// Other events
	EventTypeConditionEvaluated = "condition.evaluated"
	EventTypeVariableSet        = "variable.set"
	EventTypeErrorOccurred      = "error.occurred"
	EventTypeStateChanged       = "state.changed"
)
