// Code generated by modelgen from pkg/models/execution.go. DO NOT EDIT.

package models

import "time"

// Execution represents a single workflow execution instance.
type Execution struct {
	ID             string           `json:"id"`
	WorkflowID     string           `json:"workflow_id"`
	WorkflowName   string           `json:"workflow_name,omitempty"`
	Status         ExecutionStatus  `json:"status"`
	Input          map[string]any   `json:"input,omitempty"`
	Output         map[string]any   `json:"output,omitempty"`
	Error          string           `json:"error,omitempty"`
	NodeExecutions []*NodeExecution `json:"node_executions,omitempty"`
	Variables      map[string]any   `json:"variables,omitempty"`   // Runtime variables that override workflow variables
	StrictMode     bool             `json:"strict_mode,omitempty"` // If true, missing template variables cause execution to fail
	StartedAt      time.Time        `json:"started_at"`
	CompletedAt    *time.Time       `json:"completed_at,omitempty"`
	Duration       int64            `json:"duration,omitempty"` // milliseconds
	TriggeredBy    string           `json:"triggered_by,omitempty"`
	Metadata       map[string]any   `json:"metadata,omitempty"`
}

// ExecutionStatus represents the status of an execution.
type ExecutionStatus string

const (
	ExecutionStatusPending   ExecutionStatus = "pending"
	ExecutionStatusRunning   ExecutionStatus = "running"
	ExecutionStatusCompleted ExecutionStatus = "completed"
	ExecutionStatusFailed    ExecutionStatus = "failed"
	ExecutionStatusCancelled ExecutionStatus = "cancelled"
	ExecutionStatusTimeout   ExecutionStatus = "timeout"
)

// NodeExecution represents the execution of a single node within a workflow execution.
type NodeExecution struct {
	ID             string              `json:"id"`
	ExecutionID    string              `json:"execution_id"`
	NodeID         string              `json:"node_id"`
	NodeName       string              `json:"node_name,omitempty"`
	NodeType       string              `json:"node_type,omitempty"`
	Status         NodeExecutionStatus `json:"status"`
	Input          map[string]any      `json:"input,omitempty"`           // Input data passed to the node executor
	Output         map[string]any      `json:"output,omitempty"`          // Output data from node execution
	Config         map[string]any      `json:"config,omitempty"`          // Original node configuration (before template resolution)
	ResolvedConfig map[string]any      `json:"resolved_config,omitempty"` // Configuration after template resolution (final config used by executor)
	Error          string              `json:"error,omitempty"`
	StartedAt      time.Time           `json:"started_at"`
	CompletedAt    *time.Time          `json:"completed_at,omitempty"`
	Duration       int64               `json:"duration,omitempty"` // milliseconds
	RetryCount     int                 `json:"retry_count,omitempty"`
	Metadata       map[string]any      `json:"metadata,omitempty"`
}

// NodeExecutionStatus represents the status of a node execution.
type NodeExecutionStatus string

const (
	NodeExecutionStatusPending   NodeExecutionStatus = "pending"
	NodeExecutionStatusRunning   NodeExecutionStatus = "running"
	NodeExecutionStatusCompleted NodeExecutionStatus = "completed"
	NodeExecutionStatusFailed    NodeExecutionStatus = "failed"
	NodeExecutionStatusSkipped   NodeExecutionStatus = "skipped"
	NodeExecutionStatusCancelled NodeExecutionStatus = "cancelled"
)
