// Code generated by modelgen from pkg/models/workflow.go. DO NOT EDIT.

package models

import "time"

// Workflow represents a complete workflow definition with its DAG structure.
type Workflow struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description string         `json:"description,omitempty"`
	Version     int            `json:"version"`
	Status      WorkflowStatus `json:"status"`
	Tags        []string       `json:"tags,omitempty"`
	Nodes       []*Node        `json:"nodes"`
	Edges       []*Edge        `json:"edges"`
	Variables   map[string]any `json:"variables,omitempty"` // Workflow-level variables for template substitution
	Metadata    map[string]any `json:"metadata,omitempty"`
	CreatedBy   string         `json:"created_by,omitempty"` // User ID who created the workflow
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

// WorkflowStatus represents the status of a workflow.
type WorkflowStatus string

const (
	WorkflowStatusDraft    WorkflowStatus = "draft"
	WorkflowStatusActive   WorkflowStatus = "active"
	WorkflowStatusInactive WorkflowStatus = "inactive"
	WorkflowStatusArchived WorkflowStatus = "archived"
)

// Node represents a single node in the workflow DAG.
type Node struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Type        string         `json:"type"`
	Description string         `json:"description,omitempty"`
	Config      map[string]any `json:"config"`
	Position    *Position      `json:"position,omitempty"`
	Metadata    map[string]any `json:"metadata,omitempty"`
}

// Position represents the visual position of a node in the editor.
type Position struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
}

// LoopConfig configures a loop edge that allows controlled re-execution of a wave range.
type LoopConfig struct {
	MaxIterations int `json:"max_iterations"`
}

// Edge represents a directed edge between two nodes in the DAG.
type Edge struct {
	ID           string         `json:"id"`
	From         string         `json:"from"`
	To           string         `json:"to"`
	SourceHandle string         `json:"source_handle,omitempty"`
	Condition    string         `json:"condition,omitempty"`
	Loop         *LoopConfig    `json:"loop,omitempty"`
	Metadata     map[string]any `json:"metadata,omitempty"`
}
