name: order-processing-workflow
version: 1.0.0
description: Обработка заказа клиента

triggers:
  - type: http
    id: http-trigger-1
    config:
      path: /orders
      method: POST

nodes:
  - id: validate-order
    type: process
    handler: validateOrder
    timeout: 5s
    retry:
      max_attempts: 3
      backoff: exponential
  - id: calculate-price
    type: process
    handler: calculatePrice

edges:
  - from: validate-order
    to: calculate-price
    type: direct


