/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/executions/': RouteRecordInfo<
      '/executions/',
      '/executions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/executions/[id]': RouteRecordInfo<
      '/executions/[id]',
      '/executions/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/templates/': RouteRecordInfo<
      '/templates/',
      '/templates',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/triggers/': RouteRecordInfo<
      '/triggers/',
      '/triggers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/triggers/new': RouteRecordInfo<
      '/triggers/new',
      '/triggers/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/workflows/': RouteRecordInfo<
      '/workflows/',
      '/workflows',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/workflows/[id]': RouteRecordInfo<
      '/workflows/[id]',
      '/workflows/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/workflows/new': RouteRecordInfo<
      '/workflows/new',
      '/workflows/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/executions/index.vue': {
      routes:
        | '/executions/'
      views:
        | never
    }
    'src/pages/executions/[id].vue': {
      routes:
        | '/executions/[id]'
      views:
        | never
    }
    'src/pages/templates/index.vue': {
      routes:
        | '/templates/'
      views:
        | never
    }
    'src/pages/triggers/index.vue': {
      routes:
        | '/triggers/'
      views:
        | never
    }
    'src/pages/triggers/new.vue': {
      routes:
        | '/triggers/new'
      views:
        | never
    }
    'src/pages/workflows/index.vue': {
      routes:
        | '/workflows/'
      views:
        | never
    }
    'src/pages/workflows/[id].vue': {
      routes:
        | '/workflows/[id]'
      views:
        | never
    }
    'src/pages/workflows/new.vue': {
      routes:
        | '/workflows/new'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
