// Code generated by modelgen from pkg/models/trigger.go. DO NOT EDIT.

package models

import "time"

// Trigger represents a workflow trigger configuration.
type Trigger struct {
	ID          string         `json:"id"`
	WorkflowID  string         `json:"workflow_id"`
	Name        string         `json:"name"`
	Description string         `json:"description,omitempty"`
	Type        TriggerType    `json:"type"`
	Config      map[string]any `json:"config"`
	Enabled     bool           `json:"enabled"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	LastRun     *time.Time     `json:"last_run,omitempty"`
	NextRun     *time.Time     `json:"next_run,omitempty"`
	Metadata    map[string]any `json:"metadata,omitempty"`
}

// TriggerType represents the type of trigger.
type TriggerType string

const (
	// TriggerTypeManual represents a manual trigger (user-initiated)
	TriggerTypeManual TriggerType = "manual"
	// TriggerTypeCron represents a time-based trigger using cron expressions
	TriggerTypeCron TriggerType = "cron"
	// TriggerTypeWebhook represents an HTTP webhook trigger
	TriggerTypeWebhook TriggerType = "webhook"
	// TriggerTypeEvent represents an event-driven trigger
	TriggerTypeEvent TriggerType = "event"
	// TriggerTypeInterval represents an interval-based trigger
	TriggerTypeInterval TriggerType = "interval"
)
