// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: service_api.proto

package serviceapipb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MBFlowServiceAPI_ListWorkflows_FullMethodName    = "/serviceapi.MBFlowServiceAPI/ListWorkflows"
	MBFlowServiceAPI_GetWorkflow_FullMethodName      = "/serviceapi.MBFlowServiceAPI/GetWorkflow"
	MBFlowServiceAPI_CreateWorkflow_FullMethodName   = "/serviceapi.MBFlowServiceAPI/CreateWorkflow"
	MBFlowServiceAPI_UpdateWorkflow_FullMethodName   = "/serviceapi.MBFlowServiceAPI/UpdateWorkflow"
	MBFlowServiceAPI_DeleteWorkflow_FullMethodName   = "/serviceapi.MBFlowServiceAPI/DeleteWorkflow"
	MBFlowServiceAPI_ListExecutions_FullMethodName   = "/serviceapi.MBFlowServiceAPI/ListExecutions"
	MBFlowServiceAPI_GetExecution_FullMethodName     = "/serviceapi.MBFlowServiceAPI/GetExecution"
	MBFlowServiceAPI_StartExecution_FullMethodName   = "/serviceapi.MBFlowServiceAPI/StartExecution"
	MBFlowServiceAPI_CancelExecution_FullMethodName  = "/serviceapi.MBFlowServiceAPI/CancelExecution"
	MBFlowServiceAPI_RetryExecution_FullMethodName   = "/serviceapi.MBFlowServiceAPI/RetryExecution"
	MBFlowServiceAPI_ListTriggers_FullMethodName     = "/serviceapi.MBFlowServiceAPI/ListTriggers"
	MBFlowServiceAPI_CreateTrigger_FullMethodName    = "/serviceapi.MBFlowServiceAPI/CreateTrigger"
	MBFlowServiceAPI_UpdateTrigger_FullMethodName    = "/serviceapi.MBFlowServiceAPI/UpdateTrigger"
	MBFlowServiceAPI_DeleteTrigger_FullMethodName    = "/serviceapi.MBFlowServiceAPI/DeleteTrigger"
	MBFlowServiceAPI_GetTrigger_FullMethodName       = "/serviceapi.MBFlowServiceAPI/GetTrigger"
	MBFlowServiceAPI_ListCredentials_FullMethodName  = "/serviceapi.MBFlowServiceAPI/ListCredentials"
	MBFlowServiceAPI_CreateCredential_FullMethodName = "/serviceapi.MBFlowServiceAPI/CreateCredential"
	MBFlowServiceAPI_UpdateCredential_FullMethodName = "/serviceapi.MBFlowServiceAPI/UpdateCredential"
	MBFlowServiceAPI_DeleteCredential_FullMethodName = "/serviceapi.MBFlowServiceAPI/DeleteCredential"
	MBFlowServiceAPI_GetCredential_FullMethodName    = "/serviceapi.MBFlowServiceAPI/GetCredential"
	MBFlowServiceAPI_ListAuditLog_FullMethodName     = "/serviceapi.MBFlowServiceAPI/ListAuditLog"
)

// MBFlowServiceAPIClient is the client API for MBFlowServiceAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MBFlowServiceAPI provides programmatic access to MBFlow workflows, executions,
// triggers, credentials, and audit logs. Authentication is via system keys
// passed in gRPC metadata (x-system-key or authorization header).
type MBFlowServiceAPIClient interface {
	// Workflows
	ListWorkflows(ctx context.Context, in *ListWorkflowsRequest, opts ...grpc.CallOption) (*ListWorkflowsResponse, error)
	GetWorkflow(ctx context.Context, in *GetWorkflowRequest, opts ...grpc.CallOption) (*WorkflowResponse, error)
	CreateWorkflow(ctx context.Context, in *CreateWorkflowRequest, opts ...grpc.CallOption) (*WorkflowResponse, error)
	UpdateWorkflow(ctx context.Context, in *UpdateWorkflowRequest, opts ...grpc.CallOption) (*WorkflowResponse, error)
	DeleteWorkflow(ctx context.Context, in *DeleteWorkflowRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// Executions
	ListExecutions(ctx context.Context, in *ListExecutionsRequest, opts ...grpc.CallOption) (*ListExecutionsResponse, error)
	GetExecution(ctx context.Context, in *GetExecutionRequest, opts ...grpc.CallOption) (*ExecutionResponse, error)
	StartExecution(ctx context.Context, in *StartExecutionRequest, opts ...grpc.CallOption) (*ExecutionResponse, error)
	CancelExecution(ctx context.Context, in *CancelExecutionRequest, opts ...grpc.CallOption) (*ExecutionResponse, error)
	RetryExecution(ctx context.Context, in *RetryExecutionRequest, opts ...grpc.CallOption) (*ExecutionResponse, error)
	// Triggers
	ListTriggers(ctx context.Context, in *ListTriggersRequest, opts ...grpc.CallOption) (*ListTriggersResponse, error)
	CreateTrigger(ctx context.Context, in *CreateTriggerRequest, opts ...grpc.CallOption) (*TriggerResponse, error)
	UpdateTrigger(ctx context.Context, in *UpdateTriggerRequest, opts ...grpc.CallOption) (*TriggerResponse, error)
	DeleteTrigger(ctx context.Context, in *DeleteTriggerRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	GetTrigger(ctx context.Context, in *GetTriggerRequest, opts ...grpc.CallOption) (*TriggerResponse, error)
	// Credentials
	ListCredentials(ctx context.Context, in *ListCredentialsRequest, opts ...grpc.CallOption) (*ListCredentialsResponse, error)
	CreateCredential(ctx context.Context, in *CreateCredentialRequest, opts ...grpc.CallOption) (*CredentialResponse, error)
	UpdateCredential(ctx context.Context, in *UpdateCredentialRequest, opts ...grpc.CallOption) (*CredentialResponse, error)
	DeleteCredential(ctx context.Context, in *DeleteCredentialRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	GetCredential(ctx context.Context, in *GetCredentialRequest, opts ...grpc.CallOption) (*CredentialResponse, error)
	// Audit
	ListAuditLog(ctx context.Context, in *ListAuditLogRequest, opts ...grpc.CallOption) (*ListAuditLogResponse, error)
}

type mBFlowServiceAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewMBFlowServiceAPIClient(cc grpc.ClientConnInterface) MBFlowServiceAPIClient {
	return &mBFlowServiceAPIClient{cc}
}

func (c *mBFlowServiceAPIClient) ListWorkflows(ctx context.Context, in *ListWorkflowsRequest, opts ...grpc.CallOption) (*ListWorkflowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkflowsResponse)
	err := c.cc.Invoke(ctx, MBFlowServiceAPI_ListWorkflows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mBFlowServiceAPIClient) GetWorkflow(ctx context.Context, in *GetWorkflowRequest, opts ...grpc.CallOption) (*WorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowResponse)
	err := c.cc.Invoke(ctx, MBFlowServiceAPI_GetWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mBFlowServiceAPIClient) CreateWorkflow(ctx context.Context, in *CreateWorkflowRequest, opts ...grpc.CallOption) (*WorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowResponse)
	err := c.cc.Invoke(ctx, MBFlowServiceAPI_CreateWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mBFlowServiceAPIClient) UpdateWorkflow(ctx context.Context, in *UpdateWorkflowRequest, opts ...grpc.CallOption) (*WorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowResponse)
	err := c.cc.Invoke(ctx, MBFlowServiceAPI_UpdateWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mBFlowServiceAPIClient) DeleteWorkflow(ctx context.Context, in *DeleteWorkflowRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, MBFlowServiceAPI_DeleteWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mBFlowServiceAPIClient) ListExecutions(ctx context.Context, in *ListExecutionsRequest, opts ...grpc.CallOption) (*ListExecutionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExecutionsResponse)
	err := c.cc.Invoke(ctx, MBFlowServiceAPI_ListExecutions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mBFlowServiceAPIClient) GetExecution(ctx context.Context, in *GetExecutionRequest, opts ...grpc.CallOption) (*ExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionResponse)
	err := c.cc.Invoke(ctx, MBFlowServiceAPI_GetExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mBFlowServiceAPIClient) StartExecution(ctx context.Context, in *StartExecutionRequest, opts ...grpc.CallOption) (*ExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionResponse)
	err := c.cc.Invoke(ctx, MBFlowServiceAPI_StartExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mBFlowServiceAPIClient) CancelExecution(ctx context.Context, in *CancelExecutionRequest, opts ...grpc.CallOption) (*ExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionResponse)
	err := c.cc.Invoke(ctx, MBFlowServiceAPI_CancelExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mBFlowServiceAPIClient) RetryExecution(ctx context.Context, in *RetryExecutionRequest, opts ...grpc.CallOption) (*ExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionResponse)
	err := c.cc.Invoke(ctx, MBFlowServiceAPI_RetryExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mBFlowServiceAPIClient) ListTriggers(ctx context.Context, in *ListTriggersRequest, opts ...grpc.CallOption) (*ListTriggersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTriggersResponse)
	err := c.cc.Invoke(ctx, MBFlowServiceAPI_ListTriggers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mBFlowServiceAPIClient) CreateTrigger(ctx context.Context, in *CreateTriggerRequest, opts ...grpc.CallOption) (*TriggerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerResponse)
	err := c.cc.Invoke(ctx, MBFlowServiceAPI_CreateTrigger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mBFlowServiceAPIClient) UpdateTrigger(ctx context.Context, in *UpdateTriggerRequest, opts ...grpc.CallOption) (*TriggerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerResponse)
	err := c.cc.Invoke(ctx, MBFlowServiceAPI_UpdateTrigger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mBFlowServiceAPIClient) DeleteTrigger(ctx context.Context, in *DeleteTriggerRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, MBFlowServiceAPI_DeleteTrigger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mBFlowServiceAPIClient) GetTrigger(ctx context.Context, in *GetTriggerRequest, opts ...grpc.CallOption) (*TriggerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerResponse)
	err := c.cc.Invoke(ctx, MBFlowServiceAPI_GetTrigger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mBFlowServiceAPIClient) ListCredentials(ctx context.Context, in *ListCredentialsRequest, opts ...grpc.CallOption) (*ListCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCredentialsResponse)
	err := c.cc.Invoke(ctx, MBFlowServiceAPI_ListCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mBFlowServiceAPIClient) CreateCredential(ctx context.Context, in *CreateCredentialRequest, opts ...grpc.CallOption) (*CredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialResponse)
	err := c.cc.Invoke(ctx, MBFlowServiceAPI_CreateCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mBFlowServiceAPIClient) UpdateCredential(ctx context.Context, in *UpdateCredentialRequest, opts ...grpc.CallOption) (*CredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialResponse)
	err := c.cc.Invoke(ctx, MBFlowServiceAPI_UpdateCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mBFlowServiceAPIClient) DeleteCredential(ctx context.Context, in *DeleteCredentialRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, MBFlowServiceAPI_DeleteCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mBFlowServiceAPIClient) GetCredential(ctx context.Context, in *GetCredentialRequest, opts ...grpc.CallOption) (*CredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialResponse)
	err := c.cc.Invoke(ctx, MBFlowServiceAPI_GetCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mBFlowServiceAPIClient) ListAuditLog(ctx context.Context, in *ListAuditLogRequest, opts ...grpc.CallOption) (*ListAuditLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuditLogResponse)
	err := c.cc.Invoke(ctx, MBFlowServiceAPI_ListAuditLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MBFlowServiceAPIServer is the server API for MBFlowServiceAPI service.
// All implementations must embed UnimplementedMBFlowServiceAPIServer
// for forward compatibility.
//
// MBFlowServiceAPI provides programmatic access to MBFlow workflows, executions,
// triggers, credentials, and audit logs. Authentication is via system keys
// passed in gRPC metadata (x-system-key or authorization header).
type MBFlowServiceAPIServer interface {
	// Workflows
	ListWorkflows(context.Context, *ListWorkflowsRequest) (*ListWorkflowsResponse, error)
	GetWorkflow(context.Context, *GetWorkflowRequest) (*WorkflowResponse, error)
	CreateWorkflow(context.Context, *CreateWorkflowRequest) (*WorkflowResponse, error)
	UpdateWorkflow(context.Context, *UpdateWorkflowRequest) (*WorkflowResponse, error)
	DeleteWorkflow(context.Context, *DeleteWorkflowRequest) (*DeleteResponse, error)
	// Executions
	ListExecutions(context.Context, *ListExecutionsRequest) (*ListExecutionsResponse, error)
	GetExecution(context.Context, *GetExecutionRequest) (*ExecutionResponse, error)
	StartExecution(context.Context, *StartExecutionRequest) (*ExecutionResponse, error)
	CancelExecution(context.Context, *CancelExecutionRequest) (*ExecutionResponse, error)
	RetryExecution(context.Context, *RetryExecutionRequest) (*ExecutionResponse, error)
	// Triggers
	ListTriggers(context.Context, *ListTriggersRequest) (*ListTriggersResponse, error)
	CreateTrigger(context.Context, *CreateTriggerRequest) (*TriggerResponse, error)
	UpdateTrigger(context.Context, *UpdateTriggerRequest) (*TriggerResponse, error)
	DeleteTrigger(context.Context, *DeleteTriggerRequest) (*DeleteResponse, error)
	GetTrigger(context.Context, *GetTriggerRequest) (*TriggerResponse, error)
	// Credentials
	ListCredentials(context.Context, *ListCredentialsRequest) (*ListCredentialsResponse, error)
	CreateCredential(context.Context, *CreateCredentialRequest) (*CredentialResponse, error)
	UpdateCredential(context.Context, *UpdateCredentialRequest) (*CredentialResponse, error)
	DeleteCredential(context.Context, *DeleteCredentialRequest) (*DeleteResponse, error)
	GetCredential(context.Context, *GetCredentialRequest) (*CredentialResponse, error)
	// Audit
	ListAuditLog(context.Context, *ListAuditLogRequest) (*ListAuditLogResponse, error)
	mustEmbedUnimplementedMBFlowServiceAPIServer()
}

// UnimplementedMBFlowServiceAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMBFlowServiceAPIServer struct{}

func (UnimplementedMBFlowServiceAPIServer) ListWorkflows(context.Context, *ListWorkflowsRequest) (*ListWorkflowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkflows not implemented")
}
func (UnimplementedMBFlowServiceAPIServer) GetWorkflow(context.Context, *GetWorkflowRequest) (*WorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkflow not implemented")
}
func (UnimplementedMBFlowServiceAPIServer) CreateWorkflow(context.Context, *CreateWorkflowRequest) (*WorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWorkflow not implemented")
}
func (UnimplementedMBFlowServiceAPIServer) UpdateWorkflow(context.Context, *UpdateWorkflowRequest) (*WorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWorkflow not implemented")
}
func (UnimplementedMBFlowServiceAPIServer) DeleteWorkflow(context.Context, *DeleteWorkflowRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWorkflow not implemented")
}
func (UnimplementedMBFlowServiceAPIServer) ListExecutions(context.Context, *ListExecutionsRequest) (*ListExecutionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExecutions not implemented")
}
func (UnimplementedMBFlowServiceAPIServer) GetExecution(context.Context, *GetExecutionRequest) (*ExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExecution not implemented")
}
func (UnimplementedMBFlowServiceAPIServer) StartExecution(context.Context, *StartExecutionRequest) (*ExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartExecution not implemented")
}
func (UnimplementedMBFlowServiceAPIServer) CancelExecution(context.Context, *CancelExecutionRequest) (*ExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelExecution not implemented")
}
func (UnimplementedMBFlowServiceAPIServer) RetryExecution(context.Context, *RetryExecutionRequest) (*ExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryExecution not implemented")
}
func (UnimplementedMBFlowServiceAPIServer) ListTriggers(context.Context, *ListTriggersRequest) (*ListTriggersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTriggers not implemented")
}
func (UnimplementedMBFlowServiceAPIServer) CreateTrigger(context.Context, *CreateTriggerRequest) (*TriggerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTrigger not implemented")
}
func (UnimplementedMBFlowServiceAPIServer) UpdateTrigger(context.Context, *UpdateTriggerRequest) (*TriggerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTrigger not implemented")
}
func (UnimplementedMBFlowServiceAPIServer) DeleteTrigger(context.Context, *DeleteTriggerRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTrigger not implemented")
}
func (UnimplementedMBFlowServiceAPIServer) GetTrigger(context.Context, *GetTriggerRequest) (*TriggerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrigger not implemented")
}
func (UnimplementedMBFlowServiceAPIServer) ListCredentials(context.Context, *ListCredentialsRequest) (*ListCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCredentials not implemented")
}
func (UnimplementedMBFlowServiceAPIServer) CreateCredential(context.Context, *CreateCredentialRequest) (*CredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCredential not implemented")
}
func (UnimplementedMBFlowServiceAPIServer) UpdateCredential(context.Context, *UpdateCredentialRequest) (*CredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCredential not implemented")
}
func (UnimplementedMBFlowServiceAPIServer) DeleteCredential(context.Context, *DeleteCredentialRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCredential not implemented")
}
func (UnimplementedMBFlowServiceAPIServer) GetCredential(context.Context, *GetCredentialRequest) (*CredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCredential not implemented")
}
func (UnimplementedMBFlowServiceAPIServer) ListAuditLog(context.Context, *ListAuditLogRequest) (*ListAuditLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAuditLog not implemented")
}
func (UnimplementedMBFlowServiceAPIServer) mustEmbedUnimplementedMBFlowServiceAPIServer() {}
func (UnimplementedMBFlowServiceAPIServer) testEmbeddedByValue()                          {}

// UnsafeMBFlowServiceAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MBFlowServiceAPIServer will
// result in compilation errors.
type UnsafeMBFlowServiceAPIServer interface {
	mustEmbedUnimplementedMBFlowServiceAPIServer()
}

func RegisterMBFlowServiceAPIServer(s grpc.ServiceRegistrar, srv MBFlowServiceAPIServer) {
	// If the following call panics, it indicates UnimplementedMBFlowServiceAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MBFlowServiceAPI_ServiceDesc, srv)
}

func _MBFlowServiceAPI_ListWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkflowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MBFlowServiceAPIServer).ListWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MBFlowServiceAPI_ListWorkflows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MBFlowServiceAPIServer).ListWorkflows(ctx, req.(*ListWorkflowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MBFlowServiceAPI_GetWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MBFlowServiceAPIServer).GetWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MBFlowServiceAPI_GetWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MBFlowServiceAPIServer).GetWorkflow(ctx, req.(*GetWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MBFlowServiceAPI_CreateWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MBFlowServiceAPIServer).CreateWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MBFlowServiceAPI_CreateWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MBFlowServiceAPIServer).CreateWorkflow(ctx, req.(*CreateWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MBFlowServiceAPI_UpdateWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MBFlowServiceAPIServer).UpdateWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MBFlowServiceAPI_UpdateWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MBFlowServiceAPIServer).UpdateWorkflow(ctx, req.(*UpdateWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MBFlowServiceAPI_DeleteWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MBFlowServiceAPIServer).DeleteWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MBFlowServiceAPI_DeleteWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MBFlowServiceAPIServer).DeleteWorkflow(ctx, req.(*DeleteWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MBFlowServiceAPI_ListExecutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExecutionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MBFlowServiceAPIServer).ListExecutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MBFlowServiceAPI_ListExecutions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MBFlowServiceAPIServer).ListExecutions(ctx, req.(*ListExecutionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MBFlowServiceAPI_GetExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MBFlowServiceAPIServer).GetExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MBFlowServiceAPI_GetExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MBFlowServiceAPIServer).GetExecution(ctx, req.(*GetExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MBFlowServiceAPI_StartExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MBFlowServiceAPIServer).StartExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MBFlowServiceAPI_StartExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MBFlowServiceAPIServer).StartExecution(ctx, req.(*StartExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MBFlowServiceAPI_CancelExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MBFlowServiceAPIServer).CancelExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MBFlowServiceAPI_CancelExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MBFlowServiceAPIServer).CancelExecution(ctx, req.(*CancelExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MBFlowServiceAPI_RetryExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MBFlowServiceAPIServer).RetryExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MBFlowServiceAPI_RetryExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MBFlowServiceAPIServer).RetryExecution(ctx, req.(*RetryExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MBFlowServiceAPI_ListTriggers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTriggersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MBFlowServiceAPIServer).ListTriggers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MBFlowServiceAPI_ListTriggers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MBFlowServiceAPIServer).ListTriggers(ctx, req.(*ListTriggersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MBFlowServiceAPI_CreateTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MBFlowServiceAPIServer).CreateTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MBFlowServiceAPI_CreateTrigger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MBFlowServiceAPIServer).CreateTrigger(ctx, req.(*CreateTriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MBFlowServiceAPI_UpdateTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MBFlowServiceAPIServer).UpdateTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MBFlowServiceAPI_UpdateTrigger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MBFlowServiceAPIServer).UpdateTrigger(ctx, req.(*UpdateTriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MBFlowServiceAPI_DeleteTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MBFlowServiceAPIServer).DeleteTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MBFlowServiceAPI_DeleteTrigger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MBFlowServiceAPIServer).DeleteTrigger(ctx, req.(*DeleteTriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MBFlowServiceAPI_GetTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MBFlowServiceAPIServer).GetTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MBFlowServiceAPI_GetTrigger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MBFlowServiceAPIServer).GetTrigger(ctx, req.(*GetTriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MBFlowServiceAPI_ListCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MBFlowServiceAPIServer).ListCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MBFlowServiceAPI_ListCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MBFlowServiceAPIServer).ListCredentials(ctx, req.(*ListCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MBFlowServiceAPI_CreateCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MBFlowServiceAPIServer).CreateCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MBFlowServiceAPI_CreateCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MBFlowServiceAPIServer).CreateCredential(ctx, req.(*CreateCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MBFlowServiceAPI_UpdateCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MBFlowServiceAPIServer).UpdateCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MBFlowServiceAPI_UpdateCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MBFlowServiceAPIServer).UpdateCredential(ctx, req.(*UpdateCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MBFlowServiceAPI_DeleteCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MBFlowServiceAPIServer).DeleteCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MBFlowServiceAPI_DeleteCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MBFlowServiceAPIServer).DeleteCredential(ctx, req.(*DeleteCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MBFlowServiceAPI_GetCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MBFlowServiceAPIServer).GetCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MBFlowServiceAPI_GetCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MBFlowServiceAPIServer).GetCredential(ctx, req.(*GetCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MBFlowServiceAPI_ListAuditLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuditLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MBFlowServiceAPIServer).ListAuditLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MBFlowServiceAPI_ListAuditLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MBFlowServiceAPIServer).ListAuditLog(ctx, req.(*ListAuditLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MBFlowServiceAPI_ServiceDesc is the grpc.ServiceDesc for MBFlowServiceAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MBFlowServiceAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "serviceapi.MBFlowServiceAPI",
	HandlerType: (*MBFlowServiceAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListWorkflows",
			Handler:    _MBFlowServiceAPI_ListWorkflows_Handler,
		},
		{
			MethodName: "GetWorkflow",
			Handler:    _MBFlowServiceAPI_GetWorkflow_Handler,
		},
		{
			MethodName: "CreateWorkflow",
			Handler:    _MBFlowServiceAPI_CreateWorkflow_Handler,
		},
		{
			MethodName: "UpdateWorkflow",
			Handler:    _MBFlowServiceAPI_UpdateWorkflow_Handler,
		},
		{
			MethodName: "DeleteWorkflow",
			Handler:    _MBFlowServiceAPI_DeleteWorkflow_Handler,
		},
		{
			MethodName: "ListExecutions",
			Handler:    _MBFlowServiceAPI_ListExecutions_Handler,
		},
		{
			MethodName: "GetExecution",
			Handler:    _MBFlowServiceAPI_GetExecution_Handler,
		},
		{
			MethodName: "StartExecution",
			Handler:    _MBFlowServiceAPI_StartExecution_Handler,
		},
		{
			MethodName: "CancelExecution",
			Handler:    _MBFlowServiceAPI_CancelExecution_Handler,
		},
		{
			MethodName: "RetryExecution",
			Handler:    _MBFlowServiceAPI_RetryExecution_Handler,
		},
		{
			MethodName: "ListTriggers",
			Handler:    _MBFlowServiceAPI_ListTriggers_Handler,
		},
		{
			MethodName: "CreateTrigger",
			Handler:    _MBFlowServiceAPI_CreateTrigger_Handler,
		},
		{
			MethodName: "UpdateTrigger",
			Handler:    _MBFlowServiceAPI_UpdateTrigger_Handler,
		},
		{
			MethodName: "DeleteTrigger",
			Handler:    _MBFlowServiceAPI_DeleteTrigger_Handler,
		},
		{
			MethodName: "GetTrigger",
			Handler:    _MBFlowServiceAPI_GetTrigger_Handler,
		},
		{
			MethodName: "ListCredentials",
			Handler:    _MBFlowServiceAPI_ListCredentials_Handler,
		},
		{
			MethodName: "CreateCredential",
			Handler:    _MBFlowServiceAPI_CreateCredential_Handler,
		},
		{
			MethodName: "UpdateCredential",
			Handler:    _MBFlowServiceAPI_UpdateCredential_Handler,
		},
		{
			MethodName: "DeleteCredential",
			Handler:    _MBFlowServiceAPI_DeleteCredential_Handler,
		},
		{
			MethodName: "GetCredential",
			Handler:    _MBFlowServiceAPI_GetCredential_Handler,
		},
		{
			MethodName: "ListAuditLog",
			Handler:    _MBFlowServiceAPI_ListAuditLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_api.proto",
}
