name: ai-content-pipeline
version: 1.0.0
description: Complex AI content generation pipeline with quality checks and branching logic

triggers:
  - type: http
    id: content-trigger
    config:
      path: /api/content/generate
      method: POST
      schema:
        topic: string

nodes:
  # Initial content generation
  - id: generate-content
    name: Generate Initial Content
    type: openai-completion
    config:
      model: gpt-4o
      prompt: "Write a comprehensive blog post about {{topic}}"
      max_tokens: 2000
      temperature: 0.7
      output_key: generated_content

  # Quality analysis
  - id: analyze-quality
    name: Analyze Content Quality
    type: openai-completion
    config:
      model: gpt-4o
      prompt: "Analyze the following content and rate its quality as 'high', 'medium', or 'low'"
      max_tokens: 10
      temperature: 0.1
      output_key: quality_rating

  # Routing node
  - id: quality-router
    name: Route Based on Quality
    type: conditional-router
    config:
      input_key: quality_rating
      routes:
        high: merge-content
        medium: enhance-content
        low: regenerate-content

  # Enhancement path (medium quality)
  - id: enhance-content
    name: Enhance Content
    type: openai-completion
    config:
      model: gpt-4o
      prompt: "Improve the following content by adding examples, improving transitions, and enhancing the conclusion"
      max_tokens: 2500
      temperature: 0.6
      output_key: enhanced_content

  # Regeneration path (low quality)
  - id: regenerate-content
    name: Regenerate Content
    type: openai-completion
    config:
      model: gpt-4o
      prompt: "Write a high-quality, engaging blog post about {{topic}} with clear structure and specific examples"
      max_tokens: 2500
      temperature: 0.8
      output_key: regenerated_content

  # Merge different content versions
  - id: merge-content
    name: Merge Content Versions
    type: data-merger
    config:
      strategy: select_first_available
      sources:
        - generated_content
        - enhanced_content
        - regenerated_content
      output_key: final_content

  # Parallel translations
  - id: translate-spanish
    name: Translate to Spanish
    type: openai-completion
    config:
      model: gpt-4o
      prompt: "Translate the following content to Spanish, maintaining the tone and style"
      max_tokens: 2500
      temperature: 0.3
      output_key: content_es

  - id: translate-french
    name: Translate to French
    type: openai-completion
    config:
      model: gpt-4o
      prompt: "Translate the following content to French, maintaining the tone and style"
      max_tokens: 2500
      temperature: 0.3
      output_key: content_fr

  - id: translate-german
    name: Translate to German
    type: openai-completion
    config:
      model: gpt-4o
      prompt: "Translate the following content to German, maintaining the tone and style"
      max_tokens: 2500
      temperature: 0.3
      output_key: content_de

  # SEO metadata generation
  - id: seo-english
    name: Generate SEO Metadata (EN)
    type: openai-completion
    config:
      model: gpt-4o
      prompt: "Generate SEO metadata for the content in JSON format"
      max_tokens: 300
      temperature: 0.4
      output_key: seo_en

  - id: seo-spanish
    name: Generate SEO Metadata (ES)
    type: openai-completion
    config:
      model: gpt-4o
      prompt: "Generate SEO metadata for the Spanish content in JSON format"
      max_tokens: 300
      temperature: 0.4
      output_key: seo_es

  - id: seo-french
    name: Generate SEO Metadata (FR)
    type: openai-completion
    config:
      model: gpt-4o
      prompt: "Generate SEO metadata for the French content in JSON format"
      max_tokens: 300
      temperature: 0.4
      output_key: seo_fr

  - id: seo-german
    name: Generate SEO Metadata (DE)
    type: openai-completion
    config:
      model: gpt-4o
      prompt: "Generate SEO metadata for the German content in JSON format"
      max_tokens: 300
      temperature: 0.4
      output_key: seo_de

  # Aggregation
  - id: aggregate-results
    name: Aggregate All Results
    type: data-aggregator
    config:
      output_format: json
      fields:
        content_en: final_content
        content_es: content_es
        content_fr: content_fr
        content_de: content_de
        seo_en: seo_en
        seo_es: seo_es
        seo_fr: seo_fr
        seo_de: seo_de
      output_key: final_output

  # Publishing
  - id: publish
    name: Publish to CMS
    type: http-request
    config:
      url: https://cms.example.com/api/publish
      method: POST
      body: "{{final_output}}"

edges:
  # Main flow
  - from: generate-content
    to: analyze-quality
    type: direct

  - from: analyze-quality
    to: quality-router
    type: direct

  # Quality-based branching
  - from: quality-router
    to: merge-content
    type: conditional
    config:
      condition: quality_rating == 'high'

  - from: quality-router
    to: enhance-content
    type: conditional
    config:
      condition: quality_rating == 'medium'

  - from: quality-router
    to: regenerate-content
    type: conditional
    config:
      condition: quality_rating == 'low'

  # Merge paths
  - from: enhance-content
    to: merge-content
    type: direct

  # Loop back for re-analysis
  - from: regenerate-content
    to: analyze-quality
    type: direct
    config:
      retry: true

  # Parallel translations
  - from: merge-content
    to: translate-spanish
    type: parallel

  - from: merge-content
    to: translate-french
    type: parallel

  - from: merge-content
    to: translate-german
    type: parallel

  - from: merge-content
    to: seo-english
    type: parallel

  # SEO generation
  - from: translate-spanish
    to: seo-spanish
    type: direct

  - from: translate-french
    to: seo-french
    type: direct

  - from: translate-german
    to: seo-german
    type: direct

  # Aggregate (join all parallel branches)
  - from: seo-english
    to: aggregate-results
    type: join

  - from: seo-spanish
    to: aggregate-results
    type: join

  - from: seo-french
    to: aggregate-results
    type: join

  - from: seo-german
    to: aggregate-results
    type: join

  # Publish
  - from: aggregate-results
    to: publish
    type: direct
